name: Generate Metrics
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate habits metrics
        uses: lowlighter/metrics@v3.41
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrianeDriane
          filename: metrics.svg
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Manila
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
