name: Metrics
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrianeDriane
          template: classic
          base: ""
          config_timezone: Asia/Manila

          # Issues and PRs status
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes

          # Languages - indepth + recently used, ignore SVG
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: svg
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming, data
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming, data
          plugin_languages_recent_days: 90
          plugin_languages_recent_load: 600
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%

          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_limit: 5

          # Output
          filename: metrics.svg
          config_output: svg
